const mongoose=require('mongoose');
const {Schema}=mongoose;

const kgidSchema=new Schema({
    phoneno:{
        type:Number,
        unique:true,
        required:true
    },
    KGID:{
        type:Number,
        unique:true,
        required:true
    },
    firstname:{
        type:String,
        required:true 
    },
    middlename:{
        type:String,
        required:false 
    },
    lastname:{
        type:String,
        required:false  
    },
    dob:{
        type:Date,
        required:true 
    },
    doj:{
        type:Date,
        required:true
    },
    designation:{
        type:String,
        required:true 
    },
    address:{
        type:String,
        required:true 
    },
    address1:{
        type:String,
        required:false
    },
    pincode:{
        type:Number,
        required:true 
    },
    gender:{
        type:String,
        required:true 
    },
    candidatedistrict:{
        type:String,
        required:true 
    },
    department:{
        type:String,
        required:true 
    },
    physicalchallenge:{
        type:Boolean,
        required:true 
    },
    disability:{
        type:String,
        required:false 
    },
    percentagedisability:{
        type:Number,
        required:false   
    },
    document:{
        type:File,
        required:false
    }
});


module.exports=mongoose.model('kgidcandidate',kgidSchema);